version: '3'

x-spark-common: &spark-common
  image: bitnami/spark:3.4.2
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
    - ./utils:/opt/bitnami/spark/utils
    - ./data:/data
  networks:
    - code-with-yu
  user: root

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - airflow.env
  volumes:
    - ./jobs:/opt/airflow/jobs
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./data:/data
    - ./utils:/opt/airflow/utils
  depends_on:
    - postgres
  networks:
    - code-with-yu
  user: root

services:
  spark-master:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
      - ./data:/data

  spark-worker:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - ./data:/data
    deploy:
      replicas: 2
      mode: replicated

  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - code-with-yu

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - scheduler

  scheduler:
    <<: *airflow-common
    command: bash -c "airflow db init && airflow db migrate && airflow users create --username admin --firstname Admin --lastname Adminowy --role Admin --email admin123@gmail.com --password admin && airflow scheduler"

networks:
  code-with-yu: